---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: {{ .Values.demo.replicaCount }}
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-container
        image: "{{ .Values.demo.image.repository }}:{{ .Values.demo.image.tag }}"
        ports:
        - containerPort: {{ .Values.demo.service.Port }}
